version: '3'
services:
  frontend:
    build:
      context: ""
      dockerfile: frontend/Dockerfile.prod
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true